


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."apply_stock_balance_from_movements"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  if tg_op = 'INSERT' then
    insert into public.stock_balance (piece_ref, lot_id, quantity)
    select
      piece_ref,
      lot_id,
      sum(case when direction = 'IN' then quantity else -quantity end)::bigint as delta
    from new_table
    where piece_ref is not null
      and lot_id is not null
      and direction in ('IN','OUT')
    group by piece_ref, lot_id
    on conflict (piece_ref, lot_id)
    do update set quantity = public.stock_balance.quantity + excluded.quantity;

    delete from public.stock_balance where quantity = 0;
    return null;

  elsif tg_op = 'DELETE' then
    insert into public.stock_balance (piece_ref, lot_id, quantity)
    select
      piece_ref,
      lot_id,
      -sum(case when direction = 'IN' then quantity else -quantity end)::bigint as delta
    from old_table
    where piece_ref is not null
      and lot_id is not null
      and direction in ('IN','OUT')
    group by piece_ref, lot_id
    on conflict (piece_ref, lot_id)
    do update set quantity = public.stock_balance.quantity + excluded.quantity;

    delete from public.stock_balance where quantity = 0;
    return null;

  elsif tg_op = 'UPDATE' then
    with old_agg as (
      select piece_ref, lot_id,
             sum(case when direction = 'IN' then quantity else -quantity end)::bigint as delta
      from old_table
      where piece_ref is not null
        and lot_id is not null
        and direction in ('IN','OUT')
      group by piece_ref, lot_id
    ),
    new_agg as (
      select piece_ref, lot_id,
             sum(case when direction = 'IN' then quantity else -quantity end)::bigint as delta
      from new_table
      where piece_ref is not null
        and lot_id is not null
        and direction in ('IN','OUT')
      group by piece_ref, lot_id
    ),
    diff as (
      select
        coalesce(n.piece_ref, o.piece_ref) as piece_ref,
        coalesce(n.lot_id, o.lot_id) as lot_id,
        coalesce(n.delta, 0) - coalesce(o.delta, 0) as delta
      from new_agg n
      full join old_agg o using (piece_ref, lot_id)
      where (coalesce(n.delta, 0) - coalesce(o.delta, 0)) <> 0
    )
    insert into public.stock_balance (piece_ref, lot_id, quantity)
    select piece_ref, lot_id, delta
    from diff
    on conflict (piece_ref, lot_id)
    do update set quantity = public.stock_balance.quantity + excluded.quantity;

    delete from public.stock_balance where quantity = 0;
    return null;
  end if;

  return null;
end;
$$;


ALTER FUNCTION "public"."apply_stock_balance_from_movements"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."reset_sales_id_sequence"() RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  max_id bigint;
begin
  select coalesce(max(id), 0) into max_id from public.sales;

  perform setval(
    pg_get_serial_sequence('public.sales', 'id'),
    max_id,
    true
  );
end;
$$;


ALTER FUNCTION "public"."reset_sales_id_sequence"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."inventory" (
    "id" bigint NOT NULL,
    "piece_ref" "text" NOT NULL,
    "quantity" integer DEFAULT 0 NOT NULL,
    "location" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "lot_id" bigint NOT NULL,
    "unit_cost" numeric
);


ALTER TABLE "public"."inventory" OWNER TO "postgres";


ALTER TABLE "public"."inventory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."inventory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."lots" (
    "id" bigint NOT NULL,
    "lot_code" "text",
    "label" "text",
    "purchase_date" "date" NOT NULL,
    "supplier" "text",
    "total_pieces" integer NOT NULL,
    "total_cost" numeric(12,2) NOT NULL,
    "status" "text" DEFAULT 'draft'::"text" NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "lots_status_check" CHECK (("status" = ANY (ARRAY['draft'::"text", 'confirmed'::"text"]))),
    CONSTRAINT "lots_total_cost_check" CHECK (("total_cost" >= (0)::numeric)),
    CONSTRAINT "lots_total_pieces_check" CHECK (("total_pieces" >= 0))
);


ALTER TABLE "public"."lots" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."lots_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."lots_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."lots_id_seq" OWNED BY "public"."lots"."id";



CREATE TABLE IF NOT EXISTS "public"."stock_movements" (
    "id" bigint NOT NULL,
    "piece_ref" "text" NOT NULL,
    "lot_id" bigint,
    "direction" "text" NOT NULL,
    "quantity" integer NOT NULL,
    "unit_cost" numeric(12,4),
    "source_type" "text" NOT NULL,
    "source_id" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "comment" "text",
    CONSTRAINT "ck_stock_movements_direction" CHECK (("direction" = ANY (ARRAY['IN'::"text", 'OUT'::"text", 'ADJUST'::"text"]))),
    CONSTRAINT "ck_stock_movements_piece_ref_nonempty" CHECK (("length"(TRIM(BOTH FROM "piece_ref")) > 0)),
    CONSTRAINT "ck_stock_movements_quantity_pos" CHECK (("quantity" > 0)),
    CONSTRAINT "ck_stock_movements_source_direction" CHECK (((("source_type" = 'PURCHASE'::"text") AND ("direction" = 'IN'::"text")) OR (("source_type" = 'SALE'::"text") AND ("direction" = 'OUT'::"text")) OR (("source_type" = 'SALE_CANCEL'::"text") AND ("direction" = 'IN'::"text")) OR (("source_type" = 'SALE_EDIT'::"text") AND ("direction" = 'IN'::"text")) OR ("source_type" <> ALL (ARRAY['PURCHASE'::"text", 'SALE'::"text", 'SALE_CANCEL'::"text", 'SALE_EDIT'::"text"])))),
    CONSTRAINT "ck_stock_movements_source_type_nonempty" CHECK (("length"(TRIM(BOTH FROM "source_type")) > 0)),
    CONSTRAINT "ck_stock_movements_unit_cost_nonneg" CHECK ((("unit_cost" IS NULL) OR ("unit_cost" >= (0)::numeric))),
    CONSTRAINT "stock_movements_direction_check" CHECK (("direction" = ANY (ARRAY['IN'::"text", 'OUT'::"text", 'ADJUST'::"text"]))),
    CONSTRAINT "stock_movements_quantity_check" CHECK (("quantity" > 0)),
    CONSTRAINT "stock_movements_source_type_check" CHECK (("source_type" = ANY (ARRAY['PURCHASE'::"text", 'SALE'::"text", 'SALE_CANCEL'::"text", 'SALE_EDIT'::"text"])))
);


ALTER TABLE "public"."stock_movements" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."piece_movements" AS
 SELECT "sm"."id",
    "sm"."piece_ref",
    "sm"."created_at",
    "sm"."direction",
    "sm"."quantity",
    "sm"."unit_cost",
        CASE
            WHEN ("sm"."direction" = 'IN'::"text") THEN (("sm"."quantity")::numeric * COALESCE("sm"."unit_cost", (0)::numeric))
            WHEN ("sm"."direction" = 'OUT'::"text") THEN (((- "sm"."quantity"))::numeric * COALESCE("sm"."unit_cost", (0)::numeric))
            ELSE (("sm"."quantity")::numeric * COALESCE("sm"."unit_cost", (0)::numeric))
        END AS "total_value",
    "sm"."source_type",
    "sm"."source_id",
    "sm"."lot_id",
    "l"."lot_code",
    "l"."purchase_date" AS "lot_purchase_date",
    "l"."label" AS "lot_label",
    "l"."status" AS "lot_status",
    "sm"."comment"
   FROM ("public"."stock_movements" "sm"
     LEFT JOIN "public"."lots" "l" ON (("l"."id" = "sm"."lot_id")));


ALTER VIEW "public"."piece_movements" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sale_items" (
    "id" bigint NOT NULL,
    "sale_id" bigint NOT NULL,
    "line_index" integer NOT NULL,
    "item_kind" "text" NOT NULL,
    "set_id" "text",
    "piece_ref" "text",
    "quantity" integer NOT NULL,
    "is_partial_set" boolean DEFAULT false NOT NULL,
    "net_amount" numeric(12,2),
    "cost_amount" numeric(12,4),
    "margin_amount" numeric(12,4),
    "comment" "text",
    CONSTRAINT "sale_items_item_kind_check" CHECK (("item_kind" = ANY (ARRAY['SET'::"text", 'PIECE'::"text"]))),
    CONSTRAINT "sale_items_quantity_check" CHECK (("quantity" > 0)),
    CONSTRAINT "sale_items_set_or_piece_consistency" CHECK (((("item_kind" = 'SET'::"text") AND ("set_id" IS NOT NULL) AND ("piece_ref" IS NULL)) OR (("item_kind" = 'PIECE'::"text") AND ("piece_ref" IS NOT NULL) AND ("set_id" IS NULL))))
);


ALTER TABLE "public"."sale_items" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."sale_item_movements" AS
 SELECT "si"."id" AS "sale_item_id",
    "si"."sale_id",
    "sm"."id" AS "movement_id",
    "sm"."piece_ref",
    "sm"."direction",
    "sm"."quantity",
    "sm"."unit_cost",
    "sm"."created_at"
   FROM ("public"."sale_items" "si"
     JOIN "public"."stock_movements" "sm" ON ((("sm"."source_type" = ANY (ARRAY['SALE'::"text", 'SALE_CANCEL'::"text"])) AND ("sm"."source_id" = ("si"."id")::"text"))));


ALTER VIEW "public"."sale_item_movements" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sale_item_pieces" (
    "id" bigint NOT NULL,
    "sale_id" bigint NOT NULL,
    "sale_item_id" bigint NOT NULL,
    "piece_ref" "text" NOT NULL,
    "quantity" integer NOT NULL,
    "unit_cost" numeric,
    "lot_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "sale_item_pieces_quantity_check" CHECK (("quantity" >= 0))
);


ALTER TABLE "public"."sale_item_pieces" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."sale_item_pieces_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."sale_item_pieces_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."sale_item_pieces_id_seq" OWNED BY "public"."sale_item_pieces"."id";



CREATE SEQUENCE IF NOT EXISTS "public"."sale_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."sale_items_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."sale_items_id_seq" OWNED BY "public"."sale_items"."id";



CREATE TABLE IF NOT EXISTS "public"."sales" (
    "id" bigint NOT NULL,
    "sale_number" "text",
    "sale_type" "text" NOT NULL,
    "sales_channel" "text" NOT NULL,
    "status" "text" NOT NULL,
    "net_seller_amount" numeric(12,2) NOT NULL,
    "currency" "text" DEFAULT 'EUR'::"text" NOT NULL,
    "buyer_paid_total" numeric(12,2),
    "vat_rate" numeric(4,3),
    "total_cost_amount" numeric(12,4),
    "total_margin_amount" numeric(12,4),
    "margin_rate" numeric(4,3),
    "paid_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "comment" "text",
    CONSTRAINT "sales_sale_type_check" CHECK (("sale_type" = ANY (ARRAY['SET'::"text", 'PIECE'::"text"]))),
    CONSTRAINT "sales_sales_channel_check" CHECK (("sales_channel" = ANY (ARRAY['VINTED'::"text", 'EBAY'::"text", 'LEBONCOIN'::"text", 'DIRECT'::"text", 'OTHER'::"text"]))),
    CONSTRAINT "sales_status_check" CHECK (("status" = ANY (ARRAY['CONFIRMED'::"text", 'CANCELLED'::"text"])))
);


ALTER TABLE "public"."sales" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."sales_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."sales_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."sales_id_seq" OWNED BY "public"."sales"."id";



CREATE TABLE IF NOT EXISTS "public"."sets_bom" (
    "id" bigint NOT NULL,
    "set_id" "text" NOT NULL,
    "piece_ref" "text" NOT NULL,
    "quantity" integer NOT NULL,
    "piece_name" "text"
);


ALTER TABLE "public"."sets_bom" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."stock_per_piece" AS
 WITH "movements_signed" AS (
         SELECT "stock_movements"."piece_ref",
                CASE
                    WHEN ("stock_movements"."direction" = 'IN'::"text") THEN "stock_movements"."quantity"
                    WHEN ("stock_movements"."direction" = 'OUT'::"text") THEN (- "stock_movements"."quantity")
                    WHEN ("stock_movements"."direction" = 'ADJUST'::"text") THEN "stock_movements"."quantity"
                    ELSE 0
                END AS "signed_quantity",
                CASE
                    WHEN ("stock_movements"."direction" = 'IN'::"text") THEN (("stock_movements"."quantity")::numeric * COALESCE("stock_movements"."unit_cost", (0)::numeric))
                    WHEN ("stock_movements"."direction" = 'OUT'::"text") THEN (((- "stock_movements"."quantity"))::numeric * COALESCE("stock_movements"."unit_cost", (0)::numeric))
                    WHEN ("stock_movements"."direction" = 'ADJUST'::"text") THEN (("stock_movements"."quantity")::numeric * COALESCE("stock_movements"."unit_cost", (0)::numeric))
                    ELSE (0)::numeric
                END AS "signed_value"
           FROM "public"."stock_movements"
        )
 SELECT "piece_ref",
    "sum"("signed_quantity") AS "total_quantity",
        CASE
            WHEN ("sum"("signed_quantity") > 0) THEN ("sum"("signed_value") / ("sum"("signed_quantity"))::numeric)
            ELSE NULL::numeric
        END AS "avg_unit_cost",
    "sum"("signed_value") AS "total_value"
   FROM "movements_signed"
  GROUP BY "piece_ref"
 HAVING ("sum"("signed_quantity") > 0);


ALTER VIEW "public"."stock_per_piece" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."set_completion" AS
 WITH "piece_stats" AS (
         SELECT "b"."set_id",
            "b"."piece_ref",
            "b"."quantity" AS "bom_quantity",
            COALESCE("sp"."total_quantity", (0)::bigint) AS "stock_quantity",
            LEAST(COALESCE("sp"."total_quantity", (0)::bigint), ("b"."quantity")::bigint) AS "owned_for_one_copy",
                CASE
                    WHEN ("b"."quantity" > 0) THEN "floor"(((COALESCE("sp"."total_quantity", (0)::bigint))::numeric / ("b"."quantity")::numeric))
                    ELSE NULL::numeric
                END AS "max_sets_for_piece"
           FROM ("public"."sets_bom" "b"
             LEFT JOIN "public"."stock_per_piece" "sp" ON (("sp"."piece_ref" = "b"."piece_ref")))
          WHERE ("b"."piece_ref" IS NOT NULL)
        ), "agg" AS (
         SELECT "piece_stats"."set_id",
            "sum"("piece_stats"."bom_quantity") AS "total_parts_needed",
            "sum"("piece_stats"."owned_for_one_copy") AS "total_parts_owned",
            "min"("piece_stats"."max_sets_for_piece") AS "max_complete_sets"
           FROM "piece_stats"
          GROUP BY "piece_stats"."set_id"
        )
 SELECT "set_id",
    "total_parts_needed",
    "total_parts_owned",
        CASE
            WHEN ("total_parts_needed" > 0) THEN (("total_parts_owned" * 100.0) / ("total_parts_needed")::numeric)
            ELSE NULL::numeric
        END AS "completion_percent",
    "max_complete_sets"
   FROM "agg";


ALTER VIEW "public"."set_completion" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sets_catalog" (
    "id" "text" NOT NULL,
    "display_ref" "text" NOT NULL,
    "name" "text" NOT NULL,
    "version" "text",
    "year_start" integer,
    "year_end" integer,
    "image_url" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "theme" "text"
);


ALTER TABLE "public"."sets_catalog" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."set_with_completion" AS
 SELECT "sc"."id",
    "sc"."display_ref",
    "sc"."name",
    "sc"."version",
    "sc"."year_start",
    "sc"."year_end",
    "sc"."theme",
    "sc"."image_url",
    COALESCE("c"."total_parts_needed", (0)::bigint) AS "total_parts_needed",
    COALESCE("c"."total_parts_owned", (0)::numeric) AS "total_parts_owned",
    "c"."completion_percent",
    "c"."max_complete_sets"
   FROM ("public"."sets_catalog" "sc"
     LEFT JOIN "public"."set_completion" "c" ON (("c"."set_id" = "sc"."id")));


ALTER VIEW "public"."set_with_completion" OWNER TO "postgres";


ALTER TABLE "public"."sets_bom" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sets_bom_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."sold_pieces_journal" AS
 SELECT "sip"."piece_ref",
    "si"."item_kind" AS "source",
    "sip"."sale_id",
    "sip"."sale_item_id",
    "s"."paid_at",
    "s"."sales_channel",
    "s"."sale_type",
    "s"."status",
    "sip"."quantity",
    "sip"."unit_cost",
    (("sip"."quantity")::numeric * "sip"."unit_cost") AS "total_cost",
    ("sip"."lot_id")::"text" AS "lot_id"
   FROM (("public"."sale_item_pieces" "sip"
     JOIN "public"."sales" "s" ON (("s"."id" = "sip"."sale_id")))
     JOIN "public"."sale_items" "si" ON (("si"."id" = "sip"."sale_item_id")))
  WHERE ("s"."status" = 'CONFIRMED'::"text");


ALTER VIEW "public"."sold_pieces_journal" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stock_balance" (
    "piece_ref" "text" NOT NULL,
    "lot_id" bigint NOT NULL,
    "quantity" bigint DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."stock_balance" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."stock_journal" AS
 SELECT "id",
    "piece_ref",
    "created_at",
    "direction",
    "quantity",
    "unit_cost",
    "total_value",
    "source_type",
    "source_id",
    "lot_id",
    "lot_code",
    "lot_purchase_date",
    "lot_label",
    "lot_status",
    "comment"
   FROM "public"."piece_movements" "pm"
  ORDER BY "created_at" DESC;


ALTER VIEW "public"."stock_journal" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."stock_movements_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."stock_movements_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."stock_movements_id_seq" OWNED BY "public"."stock_movements"."id";



CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "type" "text" NOT NULL,
    "item_ref" "text" NOT NULL,
    "quantity" integer NOT NULL,
    "selling_price" numeric NOT NULL,
    "fees" numeric DEFAULT 0,
    "cost_basis" numeric,
    "net_margin" numeric GENERATED ALWAYS AS ((("selling_price" - "fees") - COALESCE("cost_basis", (0)::numeric))) STORED
);


ALTER TABLE "public"."transactions" OWNER TO "postgres";


ALTER TABLE "public"."transactions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."lots" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."lots_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."sale_item_pieces" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."sale_item_pieces_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."sale_items" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."sale_items_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."sales" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."sales_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."stock_movements" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."stock_movements_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."lots"
    ADD CONSTRAINT "lots_lot_code_key" UNIQUE ("lot_code");



ALTER TABLE ONLY "public"."lots"
    ADD CONSTRAINT "lots_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sale_item_pieces"
    ADD CONSTRAINT "sale_item_pieces_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sale_items"
    ADD CONSTRAINT "sale_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_sale_number_key" UNIQUE ("sale_number");



ALTER TABLE ONLY "public"."sets_bom"
    ADD CONSTRAINT "sets_bom_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sets_catalog"
    ADD CONSTRAINT "sets_catalog_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stock_balance"
    ADD CONSTRAINT "stock_balance_pkey" PRIMARY KEY ("piece_ref", "lot_id");



ALTER TABLE ONLY "public"."stock_movements"
    ADD CONSTRAINT "stock_movements_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_inventory_piece_ref" ON "public"."inventory" USING "btree" ("piece_ref");



CREATE INDEX "idx_sets_bom_set_id" ON "public"."sets_bom" USING "btree" ("set_id");



CREATE INDEX "idx_sets_catalog_display_ref" ON "public"."sets_catalog" USING "btree" ("display_ref");



CREATE INDEX "idx_stock_movements_piece_created_id" ON "public"."stock_movements" USING "btree" ("piece_ref", "created_at", "id");



CREATE INDEX "idx_stock_movements_piece_lot" ON "public"."stock_movements" USING "btree" ("piece_ref", "lot_id");



CREATE INDEX "idx_stock_movements_source" ON "public"."stock_movements" USING "btree" ("source_type", "source_id");



CREATE INDEX "inventory_created_at_idx" ON "public"."inventory" USING "btree" ("created_at");



CREATE INDEX "inventory_piece_lot_idx" ON "public"."inventory" USING "btree" ("piece_ref", "lot_id");



CREATE INDEX "lots_purchase_date_idx" ON "public"."lots" USING "btree" ("purchase_date" DESC);



CREATE INDEX "lots_status_idx" ON "public"."lots" USING "btree" ("status");



CREATE INDEX "sale_item_pieces_piece_ref_idx" ON "public"."sale_item_pieces" USING "btree" ("piece_ref");



CREATE INDEX "sale_item_pieces_sale_id_idx" ON "public"."sale_item_pieces" USING "btree" ("sale_id");



CREATE INDEX "sale_item_pieces_sale_item_id_idx" ON "public"."sale_item_pieces" USING "btree" ("sale_item_id");



CREATE INDEX "sale_items_piece_ref_idx" ON "public"."sale_items" USING "btree" ("piece_ref");



CREATE INDEX "sale_items_sale_id_idx" ON "public"."sale_items" USING "btree" ("sale_id");



CREATE INDEX "sale_items_sale_id_line_index_idx" ON "public"."sale_items" USING "btree" ("sale_id", "line_index");



CREATE INDEX "sale_items_set_id_idx" ON "public"."sale_items" USING "btree" ("set_id");



CREATE INDEX "sales_paid_at_idx" ON "public"."sales" USING "btree" ("paid_at");



CREATE INDEX "sales_paid_at_status_idx" ON "public"."sales" USING "btree" ("paid_at", "status");



CREATE INDEX "sales_sale_type_idx" ON "public"."sales" USING "btree" ("sale_type");



CREATE INDEX "sales_sales_channel_idx" ON "public"."sales" USING "btree" ("sales_channel");



CREATE INDEX "sales_status_idx" ON "public"."sales" USING "btree" ("status");



CREATE INDEX "stock_movements_created_at_idx" ON "public"."stock_movements" USING "btree" ("created_at" DESC);



CREATE INDEX "stock_movements_piece_ref_idx" ON "public"."stock_movements" USING "btree" ("piece_ref");



CREATE INDEX "stock_movements_source_type_id_idx" ON "public"."stock_movements" USING "btree" ("source_type", "source_id");



CREATE INDEX "stock_movements_source_type_idx" ON "public"."stock_movements" USING "btree" ("source_type");



CREATE OR REPLACE TRIGGER "trg_stock_balance_del" AFTER DELETE ON "public"."stock_movements" REFERENCING OLD TABLE AS "old_table" FOR EACH STATEMENT EXECUTE FUNCTION "public"."apply_stock_balance_from_movements"();



CREATE OR REPLACE TRIGGER "trg_stock_balance_ins" AFTER INSERT ON "public"."stock_movements" REFERENCING NEW TABLE AS "new_table" FOR EACH STATEMENT EXECUTE FUNCTION "public"."apply_stock_balance_from_movements"();



CREATE OR REPLACE TRIGGER "trg_stock_balance_upd" AFTER UPDATE ON "public"."stock_movements" REFERENCING OLD TABLE AS "old_table" NEW TABLE AS "new_table" FOR EACH STATEMENT EXECUTE FUNCTION "public"."apply_stock_balance_from_movements"();



ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_lot_id_fkey" FOREIGN KEY ("lot_id") REFERENCES "public"."lots"("id");



ALTER TABLE ONLY "public"."sale_item_pieces"
    ADD CONSTRAINT "sale_item_pieces_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES "public"."sales"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sale_item_pieces"
    ADD CONSTRAINT "sale_item_pieces_sale_item_id_fkey" FOREIGN KEY ("sale_item_id") REFERENCES "public"."sale_items"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sale_items"
    ADD CONSTRAINT "sale_items_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES "public"."sales"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sale_items"
    ADD CONSTRAINT "sale_items_set_id_fkey" FOREIGN KEY ("set_id") REFERENCES "public"."sets_catalog"("id");



ALTER TABLE ONLY "public"."sets_bom"
    ADD CONSTRAINT "sets_bom_set_id_fkey" FOREIGN KEY ("set_id") REFERENCES "public"."sets_catalog"("id") ON DELETE CASCADE;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."apply_stock_balance_from_movements"() TO "anon";
GRANT ALL ON FUNCTION "public"."apply_stock_balance_from_movements"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."apply_stock_balance_from_movements"() TO "service_role";



GRANT ALL ON FUNCTION "public"."reset_sales_id_sequence"() TO "anon";
GRANT ALL ON FUNCTION "public"."reset_sales_id_sequence"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."reset_sales_id_sequence"() TO "service_role";


















GRANT ALL ON TABLE "public"."inventory" TO "anon";
GRANT ALL ON TABLE "public"."inventory" TO "authenticated";
GRANT ALL ON TABLE "public"."inventory" TO "service_role";



GRANT ALL ON SEQUENCE "public"."inventory_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."inventory_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."inventory_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."lots" TO "anon";
GRANT ALL ON TABLE "public"."lots" TO "authenticated";
GRANT ALL ON TABLE "public"."lots" TO "service_role";



GRANT ALL ON SEQUENCE "public"."lots_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."lots_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."lots_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."stock_movements" TO "anon";
GRANT ALL ON TABLE "public"."stock_movements" TO "authenticated";
GRANT ALL ON TABLE "public"."stock_movements" TO "service_role";



GRANT ALL ON TABLE "public"."piece_movements" TO "anon";
GRANT ALL ON TABLE "public"."piece_movements" TO "authenticated";
GRANT ALL ON TABLE "public"."piece_movements" TO "service_role";



GRANT ALL ON TABLE "public"."sale_items" TO "anon";
GRANT ALL ON TABLE "public"."sale_items" TO "authenticated";
GRANT ALL ON TABLE "public"."sale_items" TO "service_role";



GRANT ALL ON TABLE "public"."sale_item_movements" TO "anon";
GRANT ALL ON TABLE "public"."sale_item_movements" TO "authenticated";
GRANT ALL ON TABLE "public"."sale_item_movements" TO "service_role";



GRANT ALL ON TABLE "public"."sale_item_pieces" TO "anon";
GRANT ALL ON TABLE "public"."sale_item_pieces" TO "authenticated";
GRANT ALL ON TABLE "public"."sale_item_pieces" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sale_item_pieces_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sale_item_pieces_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sale_item_pieces_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sale_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sale_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sale_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sales" TO "anon";
GRANT ALL ON TABLE "public"."sales" TO "authenticated";
GRANT ALL ON TABLE "public"."sales" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sales_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sets_bom" TO "anon";
GRANT ALL ON TABLE "public"."sets_bom" TO "authenticated";
GRANT ALL ON TABLE "public"."sets_bom" TO "service_role";



GRANT ALL ON TABLE "public"."stock_per_piece" TO "anon";
GRANT ALL ON TABLE "public"."stock_per_piece" TO "authenticated";
GRANT ALL ON TABLE "public"."stock_per_piece" TO "service_role";



GRANT ALL ON TABLE "public"."set_completion" TO "anon";
GRANT ALL ON TABLE "public"."set_completion" TO "authenticated";
GRANT ALL ON TABLE "public"."set_completion" TO "service_role";



GRANT ALL ON TABLE "public"."sets_catalog" TO "anon";
GRANT ALL ON TABLE "public"."sets_catalog" TO "authenticated";
GRANT ALL ON TABLE "public"."sets_catalog" TO "service_role";



GRANT ALL ON TABLE "public"."set_with_completion" TO "anon";
GRANT ALL ON TABLE "public"."set_with_completion" TO "authenticated";
GRANT ALL ON TABLE "public"."set_with_completion" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sets_bom_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sets_bom_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sets_bom_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sold_pieces_journal" TO "anon";
GRANT ALL ON TABLE "public"."sold_pieces_journal" TO "authenticated";
GRANT ALL ON TABLE "public"."sold_pieces_journal" TO "service_role";



GRANT ALL ON TABLE "public"."stock_balance" TO "anon";
GRANT ALL ON TABLE "public"."stock_balance" TO "authenticated";
GRANT ALL ON TABLE "public"."stock_balance" TO "service_role";



GRANT ALL ON TABLE "public"."stock_journal" TO "anon";
GRANT ALL ON TABLE "public"."stock_journal" TO "authenticated";
GRANT ALL ON TABLE "public"."stock_journal" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stock_movements_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stock_movements_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stock_movements_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."transactions" TO "anon";
GRANT ALL ON TABLE "public"."transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


